// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/crud/crud.proto

package crud

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Crud service

type CrudService interface {
	CreateItem(ctx context.Context, in *Employee, opts ...client.CallOption) (*ID, error)
	GetItem(ctx context.Context, in *ID, opts ...client.CallOption) (*Employee, error)
	UpdateItem(ctx context.Context, in *Employee, opts ...client.CallOption) (*ID, error)
	DeleteItem(ctx context.Context, in *ID, opts ...client.CallOption) (*ID, error)
}

type crudService struct {
	c    client.Client
	name string
}

func NewCrudService(name string, c client.Client) CrudService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "crud"
	}
	return &crudService{
		c:    c,
		name: name,
	}
}

func (c *crudService) CreateItem(ctx context.Context, in *Employee, opts ...client.CallOption) (*ID, error) {
	req := c.c.NewRequest(c.name, "Crud.CreateItem", in)
	out := new(ID)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crudService) GetItem(ctx context.Context, in *ID, opts ...client.CallOption) (*Employee, error) {
	req := c.c.NewRequest(c.name, "Crud.GetItem", in)
	out := new(Employee)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crudService) UpdateItem(ctx context.Context, in *Employee, opts ...client.CallOption) (*ID, error) {
	req := c.c.NewRequest(c.name, "Crud.UpdateItem", in)
	out := new(ID)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crudService) DeleteItem(ctx context.Context, in *ID, opts ...client.CallOption) (*ID, error) {
	req := c.c.NewRequest(c.name, "Crud.DeleteItem", in)
	out := new(ID)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Crud service

type CrudHandler interface {
	CreateItem(context.Context, *Employee, *ID) error
	GetItem(context.Context, *ID, *Employee) error
	UpdateItem(context.Context, *Employee, *ID) error
	DeleteItem(context.Context, *ID, *ID) error
}

func RegisterCrudHandler(s server.Server, hdlr CrudHandler, opts ...server.HandlerOption) error {
	type crud interface {
		CreateItem(ctx context.Context, in *Employee, out *ID) error
		GetItem(ctx context.Context, in *ID, out *Employee) error
		UpdateItem(ctx context.Context, in *Employee, out *ID) error
		DeleteItem(ctx context.Context, in *ID, out *ID) error
	}
	type Crud struct {
		crud
	}
	h := &crudHandler{hdlr}
	return s.Handle(s.NewHandler(&Crud{h}, opts...))
}

type crudHandler struct {
	CrudHandler
}

func (h *crudHandler) CreateItem(ctx context.Context, in *Employee, out *ID) error {
	return h.CrudHandler.CreateItem(ctx, in, out)
}

func (h *crudHandler) GetItem(ctx context.Context, in *ID, out *Employee) error {
	return h.CrudHandler.GetItem(ctx, in, out)
}

func (h *crudHandler) UpdateItem(ctx context.Context, in *Employee, out *ID) error {
	return h.CrudHandler.UpdateItem(ctx, in, out)
}

func (h *crudHandler) DeleteItem(ctx context.Context, in *ID, out *ID) error {
	return h.CrudHandler.DeleteItem(ctx, in, out)
}
